version: '3.4'

services:
  gatewayapi.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - SELF_URL=https://localhost:8080/
      - IDENTITY_AUTHORITY=http://IdentityService:80/
      - AUTHORITY_ISSUER=https://localhost:5000/ 
    ports:
      - "80"
      - "8080:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  identityservice:
    environment:
      - IDENTITY_AUTHORITY=http://10.0.0.10:80/
      - GW_URI=https://localhost:8080/
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "5000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: on-failure
    depends_on:
            - rabbitmq 

  team.api:
    environment:
      - IDENTITY_AUTHORITY=http://IdentityService:80/
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      - "443"
    restart: on-failure
    depends_on:
            - rabbitmq 

    
  player.api:
    environment:
      - IDENTITY_AUTHORITY=http://IdentityService:80/
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    restart: on-failure
    depends_on:
            - rabbitmq 


  sendmailservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: on-failure
    depends_on:
            - rabbitmq 
